:sectnums!:

[appendix]
[[_mapping_a_jira_system]]
== Associer un système Jira à un Système de Suivi des Incidents IKAN ALM

Il y a plusieurs moyens pour représenter un système Jira dans IKAN ALM.
Voici deux exemples expliquant comment spécifier cette association.
Notez qu'il existe encore d'autres possibilités.

=== Un (1) Système de Suivi des Incidents IKAN ALM représentela totalité du système Jira de la Machine hôte.

C'est la façon habituelle d'associer Jira à un Système de Suivi des Incidents IKAN ALM.
Pour ce faire, vous pouvez spécifier les paramètres suivants:

* URL: dans le format http(s)://<host>:<port>/jira/browse/${issueId}
* Modèle de recherche de Suivi d'Incident et Modèle d`'Identifiant de Suivi d`'Incident: les deux sont établis à [0-9A-Z][0-9A-Z][0-9A-Z]*-[0-9]+
* JiraRESTUrl: dans le format \http://<host>:<port>/rest

Ce Système de Suivi des Incidents associera les Incidents de tous les Projets Jira définis dans le système Jira.

=== Un (1) Système de Suivi des Incidents IKAN ALM par Projet Jira

Dans ce cas, un seul système Jira est représenté par plusieurs Systèmes de Suivi des Incidents IKAN ALM, en fonction du Projet.
Cela permet un contrôle plus granulaire de l'intégration du Suivi des Incidents Vous avez par exemple besoin de droits d'accès différents pour accéder au Projet A ou B, ou vous voulez peut-être ajouter des commentaires pour le Projet A, mais pas pour le projet B, etc.

Pour ce faire, vous pouvez spécifier les paramètres suivants:

* URL: dans le format http(s)://<host>:<port>/jira/browse/PROJ1KEY-${issueId}
* Modèle de recherche de Suivi d'Incident et Modèle d`'Identifiant de Suivi d`'Incident: les deux sont établis à PROJ1KEY-[0-9]+
* JiraRESTUrl: dans le format \http://<host>:<port>/rest

Ce Système de Suivi d'incidents n'associera que les Incidents du Projet Jira "PROJ1KEY".

:sectnums: