// The imagesdir attribute is only needed to display images during offline editing. Antora neglects the attribute.
:imagesdir: ../images
:description: Implement ITS Plugin How-to (English)
:revnumber: v6.0
:revdate: 02.07.2026

= How to implement an ITS plugin

== Purpose

Kobee has a pluggable architecture regarding Issue Tracking Systems. Providers can write their own Issue Tracking System (ITS) Plugins and deploy them so that they will be integrated in Kobee. This document explains how to develop and deploy such a Plugin.

== Setting up the Development Environment

The files that you need for writing an Kobee Issue Tracking System plugin are delivered in a .zip file named __kobee60_its_plugin.zip__. 

That zip file has the following directory structure:

* _src/java_
+
Contains the sources of the JiraITSPlugin, as a sample on how to create your own plugin

* _javadoc_
+
Contains the API documentation (start with index.html)

* _lib_
+
Contains the required jar files

Do the following to set up your development environment, for example in Eclipse:

. Unzip __kobee60_its_plugin.zip__ to a directory with the name you want to use in your Eclipse project.
. Open Eclipse and select: _New > Java Project_.
. Select _Create project_ from existing source and browse to the directory where you unzipped the file. If the project name is identical to the root directory of your sources, Eclipse automatically finds the source folders and puts the jar files of the _“lib”_ directory in the project's classpath.
. The Eclipse Project needs to have the following properties:
* compiler compliance Level must be set to 11
* Java JDK must be 11 or higher

== Implementation

Basically, you create a class that extends the AbstractITSPlugin class and another class that implements the ITSPluginFactory interface. Next, you implement/override the required methods. As an implementation example you can look at the Jira plugin classes (in particular JiraITSPlugin and JiraITSPluginFactory).

=== XyzITSPluginFactory class: Implement ITSPluginFactory

Create a class that implements the ITSPluginFactory interface. The class MUST have a no-argument constructor since this constructor will be called using reflection by Kobee code. Implement the method createITSPlugin() and let it return a fully configured instance of your implementing ITSPlugin class. The ITSPluginConfiguration argument is passed. It can be used to initialize your ITSPlugin object.

=== XyzITSPlugin: Extend AbstractITSPlugin

Create a class that extends the AbstractITSPlugin class. You could also directly implement the ITSPlugin interface, but this is not recommended. The following methods must be implemented:

==== List<Issue> getIssues(List<String> issueIds)

This is the most important method to implement: Kobee calls this method to get additional information on issues from the external Issue Tracking System. The method takes a single argument: a List of String Objects that represent the IDs of the Issues that need to be retrieved. The method should return the found issues, as a list of be.ikan.scm4all.plugin.issuetracking.Issue Objects. 

[NOTE]
====
All members of the Issue class are String objects and will be shown in Kobee as-is. Therefore, it might be interesting, for example, to look up the description of an issue status (e.g., “RESOLVED”) and put that in the Issue Object, instead of putting the status code (e.g., “3”) in the Issue Object.
====

==== List<PropertyInfo> getPropertyInfo() 

In this method, you specify which custom properties can/need to be set on the Issue Tracking System plugin. For every property that can be set, you create a be.ikan.scm4all.plugin.issuetracking.util.PropertyInfo object in which you specify:

* *name*: the name of the property
* *defaultValue*: the default value of the property
* *description*: a description of the property
* *required*: whether the property is required or optional
* *secured*: whether the value of the property is secure.
+
If the property is secure, the its value is encrypted in the Kobee database, and when it is shown in the Kobee GUI, its value is masked by asterisks (*)
* *choices*: a list of possible predefined values for the property. That list will be shown as a drop-down menu in the Kobee GUI

The method should return a List of PropertyInfo objects that represent the possible properties that can be set on the Issue Tracking System.

==== void testConnection()

This method should be implemented so that if a connection can be established to the Issue Tracking System with the properties specified, it should return normally, but throws an IssueTrackingException when a connection cannot be made.

==== void validate() 

This method should validate the values of all properties of the Issue Tracking System, and throw a ValidationException when some of them are invalid. 

For example:

* check whether a property that is set as required actually has a value,
* check whether a property named “port” that is supposed to have a numeric value doesn't contain alphanumerical characters,
* check whether a property doesn't contain spaces, ...

==== void addCommentToIssue(String issueId, String comment) 

This method will be called by Kobee to add a comment to a property or to change a property of a certain issue in the issue tracking system (so no impact on Kobee). The first argument represents the ID of the issue, the second represents the comment that is to be added. The idea is to have some tracking in the Issue Tracking System of what is going on in Kobee, e.g., by setting a promotion level property of the Issue, or by adding a comment to the Issue, ...

==== List<Issue> parseIssues(List<String> vcrCommitMessages)

Probably, this method must not be overridden. This method is implemented in AbstractITSPlugin. It parses the list of Version Control Repository (VCR) commit messages and searches for references to issues by matching regular expression patterns. The patterns 
are set in the Kobee GUI and can be retrieved by calling the Getter methods: getIssuePattern() and getIssueIdPattern(). The method returns a list of Issue objects that represents the issues parsed from the commit messages.


==== Getter methods

Some getter methods are defined that can be used to retrieve the standard properties that can be set on any 
Issue tracking System. Normally, they do not need to be overridden. Please refer to the chapter on Issue 
Tracking Systems in the Kobee User Guide for more information on those properties.

The getter methods are:

* *getURL()* : returns the URL that should directly link to a detailed view of an Issue
* *getUser()* : returns the User name that should be used to connect to the Issue Tracking System
* *getPassword()* : returns the password that should be used to connect to the Issue Tracking System
* *getIssuePattern()* : returns the Issue Pattern (Regular Expression) that is used to parse issue strings from VCR commit messages
* *getIssueIdPattern()* : returns the Issue Id Pattern (Regular Expression) that is used to parse the issue ids from the parsed issue strings that were found in the VCR commit messages
* *getProperties()* : returns a Map that contains the names and values of the custom properties that are set on the Issue Tracking System

== Deploying the Plugin to Kobee

In the following section, we assume that you installed Kobee in the folder _KOBEE_HOME_, that you have chosen Tomcat as your container and that it is installed in the folder _TOMCAT_HOME_.

To use your plugin in Kobee, you need to do the following:

. Shut down Tomcat and the Kobee Server
. Create a jar containing your plugin classes and copy it to `TOMCAT_HOME/webapps/kobee/WEB-INF/lib` and to `KOBEE_HOME/daemons/server/lib`
Alternatively, instead of creating a jar, you can copy your plugin classes to `TOMCAT_HOME/webapps/kobee/WEB-INF/classes` and to `KOBEE_HOME/daemons/server/classes`
. Copy all 3rd party jars that your plugin needs to `TOMCAT_HOME/webapps/kobee/WEB-INF/lib` and to `KOBEE_HOME/daemons/server/lib`
. Start Tomcat and the Kobee Server
. In Kobee, create a new Issue Tracking System and set the _Plugin Factory Class_ to the fully qualified class name of your implementation of the ITSPluginFactory interface.
In the JIRA example, this would be `be.ikan.scm4all.plugin.issuetracking.jira.JiraITSPluginFactory`.
. Link the created Issue Tracking System to a Project and add the Issue Phase to existing Levels (if needed). For further information on how to use Issue Tracking in Kobee, please refer to the Kobee User Guide.
